version: '3'
services:
  node-app:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db

  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0.28
    environment: 
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWROD: 'password'
    ports:
      - "3306:3306"
